# Generated by Django 4.2.7 on 2025-10-25 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('numero_dossier', models.CharField(max_length=50, unique=True, verbose_name='Numéro de dossier')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de consultation')),
                ('description_clinique', models.TextField(verbose_name='Description clinique')),
                ('pathologie_identifiee', models.CharField(max_length=200, verbose_name='Pathologie identifiée')),
                ('score_similarite', models.FloatField(verbose_name='Score de similarité')),
                ('fichier_source', models.CharField(blank=True, max_length=500)),
                ('criteres_valides', models.JSONField(default=dict, verbose_name='Critères diagnostiques validés')),
                ('plan_traitement', models.TextField(blank=True, verbose_name='Plan de traitement')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('archive', 'Archivé')], default='en_cours', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='pathology_search.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
