# Generated by Django 4.2.7 on 2025-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_search', '0002_medecin_consultation_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('non_valide', 'Non validé'), ('archive', 'Archivé')], default='en_cours', max_length=20),
        ),
    ]
