# Generated by Django 4.2.7 on 2025-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_search', '0003_alter_consultation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='plan_traitement_valide',
            field=models.TextField(blank=True, verbose_name='Plan de traitement validé'),
        ),
    ]
