# Generated by Django 4.2.7 on 2025-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_search', '0004_consultation_plan_traitement_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='notes_medecin',
            field=models.TextField(blank=True, verbose_name='Notes du médecin'),
        ),
    ]
