# Generated by Django 4.2.7 on 2025-11-22 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_search', '0005_consultation_notes_medecin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='affiliation_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° affiliation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Format CIN invalide (ex: AB123456)', regex='^[A-Z]{1,2}\\d{5,10}$')], verbose_name='N° CIN'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease_speciality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type maladie'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_insurance',
            field=models.BooleanField(default=False, verbose_name='A une mutuelle/assurance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° immatriculation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='GSM'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, default='MA', max_length=2, verbose_name='Nationalité (code ISO)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° de passeport'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Identifiant patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone fixe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_physician',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin correspondant'),
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conjoint(e)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treating_physician',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Médecin traitant'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance (compatibilité)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (compatibilité)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom (compatibilité)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone (compatibilité)'),
        ),
    ]
