# Generated by Django 4.2.7 on 2025-11-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology_search', '0006_alter_patient_options_patient_affiliation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de dossier (compatibilité)'),
        ),
    ]
